version: '3'
services:   
     
  postgres:
    image: postgres:9.6
    restart: always
    ports:
      - 5434:5432
    build:
      context: postgresql
      dockerfile: Dockerfile
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: ruread,ruauth,ruwrite
    networks:
      - default
      
  app:
    image: ruchallenge
    build:
      context: .
      dockerfile: src/Presentation.API/Dockerfile
    ports:
      - 9001:80
    links:
      - postgres  
    volumes:
      - logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    networks:
      - default
        
volumes:
  pg-data:
  logs:
    external: true
networks:
  default:
